name: 'Carbon Action'
description: 'Action for generating beautiful images of code using carbon.now.sh'
inputs:
  code:
    description: 'The Code to generate the image with'
    required: true
    default: 'console.log("Hello World");'
  backgroundColor:
    description: "The background color of the generated image"
    required: false
    default: "rgba(171, 184, 195, 1)"	
  dropShadow:
    description: "Turn on/off the shadow of the generated image"
    required: false
    default: "true"
  dropShadowBlurRadius:
    description: "The blur radius of the shadow"
    required: false
    default: "68px"
  dropShadowOffsetY:
    description: "Shadow y offset"
    required: false
    default: "20px"
  exportSize:
    description: "The resolution of exported image, e.g. 1x, 3x"
    required: false
    default: "2x"
  fontSize:
    description: "Font size of the code"
    required: false
    default: "14px"
  fontFamily:
    description: "Font family of the code"
    required: false
    default: "Hack"
  firstLineNumber:
    description: "First line number"
    required: false
    default: "1"
  language:
    description: "Programing language for proper code highlighting"
    required: false
    default: "auto"
  lineNumbers:
    description: "Turn on/off line number"
    required: false
    default: "false"
  paddingHorizontal:
    description: "Horizontal padding"
    required: false
    default: "56px"
  paddingVertical:
    description: "Vertical padding"
    required: false
    default: "56px"
  theme:
    description: "The color theme"
    required: false
    default: "material"
  watermark:
    description: "Turn on/off watermark"
    required: false
    default: "false"
  widthAdjustment:
    description: "Turn on/off width adjustment"
    required: false
    default: "true"
  windowControls:
    description: "Turn on/off window controls"
    required: false
    default: "true"
  windowTheme:
    description: "Window theme"
    required: false
    default: "none"
runs:
  using: "composite"
  steps:
    - name: Install Chrome
      run: |
        curl -sSL https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 2> /dev/null
        sudo echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" | sudo tee -a /etc/apt/sources.list.d/google-chrome.list
        sudo apt update -y && sudo apt install -y google-chrome-stable
      shell: bash
    - name: Install Python dependencies
      run: pip3 install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - name: Run Server and generate image
      run: |
        python3 ${{ github.action_path }}/app.py &
        sleep 20 &&
        curl -G \
          --data-urlencode "code=${{ inputs.code }}" \
          --data-urlencode "backgroundColor=${{ inputs.backgroundColor }}" \
          --data-urlencode "dropShadow=${{ inputs.dropShadow }}" \
          --data-urlencode "dropShadowBlurRadius=${{ inputs.dropShadowBlurRadius }}" \
          --data-urlencode "dropShadowOffsetY=${{ inputs.dropShadowOffsetY }}" \
          --data-urlencode "exportSize=${{ inputs.exportSize }}" \
          --data-urlencode "fontSize=${{ inputs.fontSize }}" \
          --data-urlencode "fontFamily=${{ inputs.fontFamily }}" \
          --data-urlencode "firstLineNumber=${{ inputs.firstLineNumber }}" \
          --data-urlencode "language=${{ inputs.language }}" \
          --data-urlencode "lineNumbers=${{ inputs.lineNumbers }}" \
          --data-urlencode "paddingHorizontal=${{ inputs.paddingHorizontal }}" \
          --data-urlencode "paddingVertical=${{ inputs.paddingVertical }}" \
          --data-urlencode "theme=${{ inputs.theme }}" \
          --data-urlencode "watermark=${{ inputs.watermark }}" \
          --data-urlencode "widthAdjustment=${{ inputs.widthAdjustment }}" \
          --data-urlencode "windowControls=${{ inputs.windowControls }}" \
          --data-urlencode "windowTheme=${{ inputs.windowTheme }}" \
          "localhost:5000/" \
          --output code.png
      shell: bash